### ISSUE TITLE
Adding chapterpic changes header text

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/community-mapping#28]
Hi @andresgnlez 
Not sure why the header style is changing internally when I add an image box before it. 

This is the code I am using
<div class="c-box-image">
    <img src="/images/posts/2/chapterpic-design.tif" alt="chapterpic-design">
  </div>
  
Different header levels seem to be denoted with # and ##, etc.

![screen shot 2016-06-22 at 1 46 33 pm](https://cloud.githubusercontent.com/assets/17725960/16277243/230b5b08-3880-11e6-859d-162032e98d22.png)
![screen shot 2016-06-22 at 1 46 41 pm](https://cloud.githubusercontent.com/assets/17725960/16277244/230e1d2a-3880-11e6-84d1-8846799f0999.png)

**Comment by shanikadhettige** [comment]
It however is not a problem here, coding appears same to me.. 
![screen shot 2016-06-22 at 2 15 12 pm](https://cloud.githubusercontent.com/assets/17725960/16278269/49ac5a1a-3884-11e6-9dd6-98cc9d4bfb9b.png)

**Comment by andresgnlez** [comment]
Hi @shanikadhettige,

it seems you are uploading tif-format images. I would recommend you convert them to `.png` or `.jpg`. Those formats are more appropiated for websites (and less problematic) than `.tif` one.

You can do this easily with a converter like this: https://convertio.co/tiff-png/

Regarding headers.. I just inspect the code, and it seems when you create a table above you forgot to close it properly and that's produced a wrong-style cascade (that's why you see everything wrongly). Now it's fixed.

**Comment by shanikadhettige** [comment]
Hi 
I changed all files to png and added the / where I thinkI missed it. @andresgnlez Can you re-deploy and we can see if the pictures fix?
If fixed, please close

**Comment by andresgnlez** [comment]
Images are not still showing up, are you changing the image's format manually? I recommend you convert them and replace the current ones with the new ones. Usually changing image's format manually can corrupt the image itself. I just try converting one and replacing it and it worked.

**Comment by shanikadhettige** [comment]
Tried redoing all but one file in section 2. Can you try now?

**Comment by andresgnlez** [comment]
Yes, images are showing up now, good job! Just a couple of things:

- Avoid using spaces in image's name like this: https://github.com/Vizzuality/community-mapping/commit/0fcfb90ca175290092fc5b43bd7fbbaffd867066 . Instead, use dashes `-` or underscores `_` if needed.

- If it's possible, remove .tif images from the website, they are taking a lot of space and we are not using them any longer.

Feel free to close this issue if everything is fine.

Thanks!

**Comment by shanikadhettige** [comment]
Sure

**Comment by shanikadhettige** [comment]
@andresgnlez Deleted .tifs and all unused images
