### ISSUE TITLE
workflow

### ISSUE THREAD

**Issue by andresgnlez** [Vizzuality/community-mapping#44]
Hi, I have seen you are doing pull request to `master` branch and merge them automatically. In order to keep `master` branch "healthy" and have a better control, please make pull request against `develop` branch. To do this, when you create the pull request, change the `base` selector to `develop` like this: 

<img width="372" alt="captura de pantalla 2016-06-23 a las 9 45 06" src="https://cloud.githubusercontent.com/assets/999124/16295451/4f416f76-3927-11e6-8280-e9073a652fee.png">

After this, assign me the pull request...

<img width="404" alt="captura de pantalla 2016-06-23 a las 9 46 36" src="https://cloud.githubusercontent.com/assets/999124/16295476/689f663a-3927-11e6-83f6-2ddcc10aae10.png">

... and I will be notified via email. I will check the new changes locally and I will merge the pull request personally (no need for you to do it) if everything is OK... Otherwise, I'll notify you what is wrong /missing and we can fix it in the pull request itself. This way, we control better every change and we avoid contaminate `master` branch (the live site) with errors.

Ah! Last thing, if you forgot to add or correct something in a Pull Request, you can update it just uploading the changes in the same branch. This way we avoid create several Pull Request to change little things.

It this OK for you? If you have any question, just ask me.

Take care,
Andrés G.

**Comment by shanikadhettige** [comment]
Ok, thanks, I think I got it right this time! If OK now pls close
